CREATE TABLE podcast (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	feed_url varchar(2048) NOT NULL,
	date_added timestamp NOT NULL,
	feed_web_url varchar(2048),
	feed_image_url varchar(2048),
	feed_title varchar(2048),
	feed_description varchar(2048),
	CONSTRAINT podcast_pkey PRIMARY KEY (id)
);

CREATE TABLE podcast_tags (
	podcast_id int8 REFERENCES podcast (id),
	tags varchar(2048) NOT NULL
);